// Mocks generated by Mockito 5.4.6 from annotations
// in herdapp/test/features/social/chat_messaging/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:herdapp/core/barrels/providers.dart' as _i3;
import 'package:herdapp/features/social/chat_messaging/data/enums/message_type.dart'
    as _i5;
import 'package:herdapp/features/social/chat_messaging/data/models/message/message_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageModel_0 extends _i1.SmartFake implements _i2.MessageModel {
  _FakeMessageModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pageSize => (super.noSuchMethod(
        Invocation.getter(#pageSize),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<_i2.MessageModel> sendEncryptedDirect({
    required String? chatId,
    required String? senderId,
    required String? content,
    _i5.MessageType? type = _i5.MessageType.text,
    String? replyToMessageId,
    Map<String, dynamic>? media,
    String? senderName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEncryptedDirect,
          [],
          {
            #chatId: chatId,
            #senderId: senderId,
            #content: content,
            #type: type,
            #replyToMessageId: replyToMessageId,
            #media: media,
            #senderName: senderName,
          },
        ),
        returnValue: _i4.Future<_i2.MessageModel>.value(_FakeMessageModel_0(
          this,
          Invocation.method(
            #sendEncryptedDirect,
            [],
            {
              #chatId: chatId,
              #senderId: senderId,
              #content: content,
              #type: type,
              #replyToMessageId: replyToMessageId,
              #media: media,
              #senderName: senderName,
            },
          ),
        )),
      ) as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<_i2.MessageModel> sendEncryptedMedia({
    required String? chatId,
    required String? senderId,
    required _i6.File? mediaFile,
    required _i5.MessageType? mediaType,
    String? caption,
    String? replyToMessageId,
    String? senderName,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEncryptedMedia,
          [],
          {
            #chatId: chatId,
            #senderId: senderId,
            #mediaFile: mediaFile,
            #mediaType: mediaType,
            #caption: caption,
            #replyToMessageId: replyToMessageId,
            #senderName: senderName,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i4.Future<_i2.MessageModel>.value(_FakeMessageModel_0(
          this,
          Invocation.method(
            #sendEncryptedMedia,
            [],
            {
              #chatId: chatId,
              #senderId: senderId,
              #mediaFile: mediaFile,
              #mediaType: mediaType,
              #caption: caption,
              #replyToMessageId: replyToMessageId,
              #senderName: senderName,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<_i6.File?> getDecryptedMedia({
    required _i2.MessageModel? message,
    required String? currentUserId,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedMedia,
          [],
          {
            #message: message,
            #currentUserId: currentUserId,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i4.Future<_i6.File?>.value(),
      ) as _i4.Future<_i6.File?>);

  // @override
  // _i4.Stream<List<_i2.MessageModel>> getChatMessages(
  //   String? chatId, {
  //   int? limit = 50,
  //   _i7.DocumentSnapshot<Object?>? lastDocument,
  // }) =>
  //     (super.noSuchMethod(
  //       Invocation.method(
  //         #getChatMessages,
  //         [chatId],
  //         {
  //           #limit: limit,
  //           #lastDocument: lastDocument,
  //         },
  //       ),
  //       returnValue: _i4.Stream<List<_i2.MessageModel>>.empty(),
  //     ) as _i4.Stream<List<_i2.MessageModel>>);

  @override
  _i4.Future<List<_i2.MessageModel>> fetchMessagePage({
    required String? chatId,
    _i7.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMessagePage,
          [],
          {
            #chatId: chatId,
            #lastDocument: lastDocument,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.MessageModel>>.value(<_i2.MessageModel>[]),
      ) as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Stream<_i2.MessageModel?> getMessageById(
    String? chatId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [
            chatId,
            messageId,
          ],
        ),
        returnValue: _i4.Stream<_i2.MessageModel?>.empty(),
      ) as _i4.Stream<_i2.MessageModel?>);

  @override
  _i4.Future<_i2.MessageModel> sendMessage({
    required String? chatId,
    required String? senderId,
    required String? content,
    _i5.MessageType? type = _i5.MessageType.text,
    String? replyToMessageId,
    Map<String, dynamic>? mediaData,
    String? senderName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #chatId: chatId,
            #senderId: senderId,
            #content: content,
            #type: type,
            #replyToMessageId: replyToMessageId,
            #mediaData: mediaData,
            #senderName: senderName,
          },
        ),
        returnValue: _i4.Future<_i2.MessageModel>.value(_FakeMessageModel_0(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #chatId: chatId,
              #senderId: senderId,
              #content: content,
              #type: type,
              #replyToMessageId: replyToMessageId,
              #mediaData: mediaData,
              #senderName: senderName,
            },
          ),
        )),
      ) as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<void> markMessagesAsRead(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessagesAsRead,
          [
            chatId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleMessageReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleMessageReaction,
          [],
          {
            #messageId: messageId,
            #userId: userId,
            #emoji: emoji,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> editMessage({
    required String? messageId,
    required String? newContent,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editMessage,
          [],
          {
            #messageId: messageId,
            #newContent: newContent,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteMessage(
    String? chatId,
    String? messageId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteMessage,
          [
            chatId,
            messageId,
            currentUserId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> deleteMessageWithValidation({
    required String? chatId,
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessageWithValidation,
          [],
          {
            #chatId: chatId,
            #messageId: messageId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.MessageModel>> searchMessages({
    required String? chatId,
    required String? query,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #chatId: chatId,
            #query: query,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.MessageModel>>.value(<_i2.MessageModel>[]),
      ) as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Stream<List<_i2.MessageModel>> encryptedMessagesStream(
    String? chatId, {
    int? limit = 50,
    _i7.DocumentSnapshot<Object?>? last,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptedMessagesStream,
          [chatId],
          {
            #limit: limit,
            #last: last,
          },
        ),
        returnValue: _i4.Stream<List<_i2.MessageModel>>.empty(),
      ) as _i4.Stream<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel?> getEncryptedMessage(
    String? chatId,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEncryptedMessage,
          [
            chatId,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.MessageModel?>.value(),
      ) as _i4.Future<_i2.MessageModel?>);

  @override
  _i4.Stream<List<_i2.MessageModel>> legacyMessagesStream(
    String? chatId, {
    int? limit = 50,
    _i7.DocumentSnapshot<Object?>? last,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyMessagesStream,
          [chatId],
          {
            #limit: limit,
            #last: last,
          },
        ),
        returnValue: _i4.Stream<List<_i2.MessageModel>>.empty(),
      ) as _i4.Stream<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel> sendPlaintext({
    required String? chatId,
    required String? senderId,
    required String? content,
    _i5.MessageType? type = _i5.MessageType.text,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPlaintext,
          [],
          {
            #chatId: chatId,
            #senderId: senderId,
            #content: content,
            #type: type,
          },
        ),
        returnValue: _i4.Future<_i2.MessageModel>.value(_FakeMessageModel_0(
          this,
          Invocation.method(
            #sendPlaintext,
            [],
            {
              #chatId: chatId,
              #senderId: senderId,
              #content: content,
              #type: type,
            },
          ),
        )),
      ) as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<void> toggleReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleReaction,
          [],
          {
            #messageId: messageId,
            #userId: userId,
            #emoji: emoji,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> editPlaintext({
    required String? messageId,
    required String? userId,
    required String? newContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPlaintext,
          [],
          {
            #messageId: messageId,
            #userId: userId,
            #newContent: newContent,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlaintext({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlaintext,
          [],
          {
            #messageId: messageId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markRead(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRead,
          [
            chatId,
            userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MessageModel>> searchPlaintext({
    required String? chatId,
    required String? query,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlaintext,
          [],
          {
            #chatId: chatId,
            #query: query,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.MessageModel>>.value(<_i2.MessageModel>[]),
      ) as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<int> getMessageCount(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #getMessageCount,
          [chatId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  // @override
  // _i4.Future<List<_i2.MessageModel>> fetchAllMessages(String? chatId) =>
  //     (super.noSuchMethod(
  //       Invocation.method(
  //         #fetchAllMessages,
  //         [chatId],
  //       ),
  //       returnValue:
  //           _i4.Future<List<_i2.MessageModel>>.value(<_i2.MessageModel>[]),
  //     ) as _i4.Future<List<_i2.MessageModel>>);

  // @override
  // _i4.Future<List<_i2.MessageModel>> fetchLatestMessages(
  //   String? chatId, {
  //   required int? limit,
  //   DateTime? afterTimestamp,
  // }) =>
  //     (super.noSuchMethod(
  //       Invocation.method(
  //         #fetchLatestMessages,
  //         [chatId],
  //         {
  //           #limit: limit,
  //           #afterTimestamp: afterTimestamp,
  //         },
  //       ),
  //       returnValue:
  //           _i4.Future<List<_i2.MessageModel>>.value(<_i2.MessageModel>[]),
  //     ) as _i4.Future<List<_i2.MessageModel>>);
}
