// Mocks generated by Mockito 5.4.6 from annotations
// in herdapp/test/features/social/chat_messaging/message_repository_test_simple.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i12;
import 'dart:typed_data' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i9;
import 'package:cryptography/cryptography.dart' as _i2;
import 'package:flutter/services.dart' as _i4;
import 'package:herdapp/features/social/chat_messaging/data/crypto/chat_crypto_service.dart'
    as _i5;
import 'package:herdapp/features/social/chat_messaging/data/models/chat/chat_model.dart'
    as _i3;
import 'package:herdapp/features/social/chat_messaging/data/repositories/chat_repository.dart'
    as _i15;
import 'package:herdapp/features/social/feed/providers/feed_type_provider.dart'
    as _i13;
import 'package:herdapp/features/user/user_profile/data/models/alt_connection_request_model.dart'
    as _i14;
import 'package:herdapp/features/user/user_profile/data/models/user_model.dart'
    as _i11;
import 'package:herdapp/features/user/user_profile/data/repositories/user_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSimplePublicKey_0 extends _i1.SmartFake
    implements _i2.SimplePublicKey {
  _FakeSimplePublicKey_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecretKey_1 extends _i1.SmartFake implements _i2.SecretKey {
  _FakeSecretKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatModel_2 extends _i1.SmartFake implements _i3.ChatModel {
  _FakeChatModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ChatCryptoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatCryptoService extends _i1.Mock implements _i5.ChatCryptoService {
  MockChatCryptoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> exportPublicIdentityKeyBase64() => (super.noSuchMethod(
        Invocation.method(
          #exportPublicIdentityKeyBase64,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #exportPublicIdentityKeyBase64,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> hasStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #hasStoredKeys,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> deleteStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #deleteStoredKeys,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> ensureKeyPairExists() => (super.noSuchMethod(
        Invocation.method(
          #ensureKeyPairExists,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.SimplePublicKey> getPublicIdentityKey() => (super.noSuchMethod(
        Invocation.method(
          #getPublicIdentityKey,
          [],
        ),
        returnValue:
            _i6.Future<_i2.SimplePublicKey>.value(_FakeSimplePublicKey_0(
          this,
          Invocation.method(
            #getPublicIdentityKey,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SimplePublicKey>);

  @override
  _i6.Future<_i2.SecretKey> deriveDirectChatKey({
    required _i8.Uint8List? otherPublicKeyBytes,
    required String? chatId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveDirectChatKey,
          [],
          {
            #otherPublicKeyBytes: otherPublicKeyBytes,
            #chatId: chatId,
          },
        ),
        returnValue: _i6.Future<_i2.SecretKey>.value(_FakeSecretKey_1(
          this,
          Invocation.method(
            #deriveDirectChatKey,
            [],
            {
              #otherPublicKeyBytes: otherPublicKeyBytes,
              #chatId: chatId,
            },
          ),
        )),
      ) as _i6.Future<_i2.SecretKey>);

  @override
  _i6.Future<Map<String, dynamic>> encryptPayload({
    required _i2.SecretKey? key,
    required Map<String, dynamic>? plaintext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptPayload,
          [],
          {
            #key: key,
            #plaintext: plaintext,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> decryptPayload({
    required _i2.SecretKey? key,
    required Map<String, dynamic>? encrypted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptPayload,
          [],
          {
            #key: key,
            #encrypted: encrypted,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.SimplePublicKey> ensureIdentityKeyPublished(
    _i9.FirebaseFirestore? firestore,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureIdentityKeyPublished,
          [
            firestore,
            userId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.SimplePublicKey>.value(_FakeSimplePublicKey_0(
          this,
          Invocation.method(
            #ensureIdentityKeyPublished,
            [
              firestore,
              userId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SimplePublicKey>);

  @override
  _i6.Future<_i8.Uint8List?> getPeerPublicKeyBytes(
    _i9.FirebaseFirestore? firestore,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeerPublicKeyBytes,
          [
            firestore,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i8.Uint8List?>.value(),
      ) as _i6.Future<_i8.Uint8List?>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i10.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> createUser(
    String? userId,
    _i11.UserModel? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            userId,
            user,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i11.UserModel?> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i6.Future<_i11.UserModel?>.value(),
      ) as _i6.Future<_i11.UserModel?>);

  @override
  _i6.Future<void> updateUser(
    String? userId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            userId,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<_i11.UserModel?> streamUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #streamUser,
          [userId],
        ),
        returnValue: _i6.Stream<_i11.UserModel?>.empty(),
      ) as _i6.Stream<_i11.UserModel?>);

  @override
  _i6.Future<String> uploadImage({
    required String? userId,
    required _i12.File? file,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [],
          {
            #userId: userId,
            #file: file,
            #type: type,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #userId: userId,
              #file: file,
              #type: type,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> incrementUserPoints(
    String? userId,
    int? points,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementUserPoints,
          [
            userId,
            points,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.UserModel>> searchUsers(
    String? query, {
    _i13.FeedType? profileType = _i13.FeedType.public,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
          {#profileType: profileType},
        ),
        returnValue: _i6.Future<List<_i11.UserModel>>.value(<_i11.UserModel>[]),
      ) as _i6.Future<List<_i11.UserModel>>);

  @override
  _i6.Future<List<_i11.UserModel>> searchAll(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAll,
          [query],
        ),
        returnValue: _i6.Future<List<_i11.UserModel>>.value(<_i11.UserModel>[]),
      ) as _i6.Future<List<_i11.UserModel>>);

  @override
  _i6.Future<List<_i11.UserModel>> searchByUsername(
    String? username, {
    _i13.FeedType? profileType = _i13.FeedType.public,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByUsername,
          [username],
          {#profileType: profileType},
        ),
        returnValue: _i6.Future<List<_i11.UserModel>>.value(<_i11.UserModel>[]),
      ) as _i6.Future<List<_i11.UserModel>>);

  @override
  _i6.Future<List<_i11.UserModel>> searchByFullName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByFullName,
          [query],
        ),
        returnValue: _i6.Future<List<_i11.UserModel>>.value(<_i11.UserModel>[]),
      ) as _i6.Future<List<_i11.UserModel>>);

  @override
  _i6.Future<bool> isUsernameAvailable(String? username) => (super.noSuchMethod(
        Invocation.method(
          #isUsernameAvailable,
          [username],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i11.UserModel?> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i6.Future<_i11.UserModel?>.value(),
      ) as _i6.Future<_i11.UserModel?>);

  @override
  _i6.Future<void> followUser(
    String? userId,
    String? followUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [
            userId,
            followUserId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unfollowUser(
    String? userId,
    String? unfollowUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [
            userId,
            unfollowUserId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isFollowing(
    String? userId,
    String? otherUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFollowing,
          [
            userId,
            otherUserId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i11.UserModel>> getFollowers(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i11.UserModel>>.empty(),
      ) as _i6.Stream<List<_i11.UserModel>>);

  @override
  _i6.Stream<List<_i11.UserModel>> getFollowing(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i11.UserModel>>.empty(),
      ) as _i6.Stream<List<_i11.UserModel>>);

  @override
  _i6.Future<int?> getFollowerCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFollowerCount,
          [userId],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<int?> getFollowingCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFollowingCount,
          [userId],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<String> uploadAltImage({
    required String? userId,
    required _i12.File? file,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAltImage,
          [],
          {
            #userId: userId,
            #file: file,
            #type: type,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAltImage,
            [],
            {
              #userId: userId,
              #file: file,
              #type: type,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> requestAltConnection(
    String? userId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestAltConnection,
          [
            userId,
            targetUserId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> acceptAltConnection(
    String? userId,
    String? requesterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptAltConnection,
          [
            userId,
            requesterId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> rejectAltConnection(
    String? userId,
    String? requesterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectAltConnection,
          [
            userId,
            requesterId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i14.AltConnectionRequest>> getPendingConnectionRequests(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingConnectionRequests,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i14.AltConnectionRequest>>.empty(),
      ) as _i6.Stream<List<_i14.AltConnectionRequest>>);

  @override
  _i6.Future<bool> hasAltConnectionRequest(
    String? requesterId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAltConnectionRequest,
          [
            requesterId,
            targetUserId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> areAltlyConnected(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #areAltlyConnected,
          [
            userId1,
            userId2,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<String>> getAltConnectionIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAltConnectionIds,
          [userId],
        ),
        returnValue: _i6.Stream<List<String>>.empty(),
      ) as _i6.Stream<List<String>>);

  @override
  _i6.Future<int> getAltConnectionCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAltConnectionCount,
          [userId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> hasAltProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasAltProfile,
          [userId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> updateAltProfile(
    String? userId,
    Map<String, dynamic>? altData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAltProfile,
          [
            userId,
            altData,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addAltConnection(
    String? userId,
    String? connectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAltConnection,
          [
            userId,
            connectionId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeAltConnection(
    String? userId,
    String? connectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAltConnection,
          [
            userId,
            connectionId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isAltlyConnected(
    String? userId,
    String? otherUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAltlyConnected,
          [
            userId,
            otherUserId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> pinPostToProfile(
    String? userId,
    String? postId, {
    bool? isAlt = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinPostToProfile,
          [
            userId,
            postId,
          ],
          {#isAlt: isAlt},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unpinPostFromProfile(
    String? userId,
    String? postId, {
    bool? isAlt = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinPostFromProfile,
          [
            userId,
            postId,
          ],
          {#isAlt: isAlt},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getPinnedPosts(
    String? userId, {
    bool? isAlt = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedPosts,
          [userId],
          {#isAlt: isAlt},
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> isPostPinnedToProfile(
    String? userId,
    String? postId, {
    bool? isAlt = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPostPinnedToProfile,
          [
            userId,
            postId,
          ],
          {#isAlt: isAlt},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> markAccountForDeletion(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAccountForDeletion,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAccountDeletion(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cancelAccountDeletion,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isAccountMarkedForDeletion(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAccountMarkedForDeletion,
          [userId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<DateTime?> getAccountDeletionDate(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountDeletionDate,
          [userId],
        ),
        returnValue: _i6.Future<DateTime?>.value(),
      ) as _i6.Future<DateTime?>);

  @override
  _i6.Future<int?> getDaysUntilPermanentDeletion(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDaysUntilPermanentDeletion,
          [userId],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<Map<String, dynamic>> requestDataExport(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDataExport,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> hasPendingDataExport(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasPendingDataExport,
          [userId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getDataExportStatus(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataExportStatus,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> resetDataExportRequest(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetDataExportRequest,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getUserExportData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserExportData,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> permanentlyDeleteAccount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteAccount,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getAccountsReadyForDeletion() => (super.noSuchMethod(
        Invocation.method(
          #getAccountsReadyForDeletion,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i15.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ChatModel?> getOrCreateDirectChat({
    required String? currentUserId,
    required String? otherUserId,
    String? otherUserName,
    String? otherUserUsername,
    String? otherUserProfileImage,
    String? otherUserAltProfileImage,
    bool? isAlt = false,
    String? currentUserName,
    String? currentUserProfileImage,
    String? currentUserAltProfileImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateDirectChat,
          [],
          {
            #currentUserId: currentUserId,
            #otherUserId: otherUserId,
            #otherUserName: otherUserName,
            #otherUserUsername: otherUserUsername,
            #otherUserProfileImage: otherUserProfileImage,
            #otherUserAltProfileImage: otherUserAltProfileImage,
            #isAlt: isAlt,
            #currentUserName: currentUserName,
            #currentUserProfileImage: currentUserProfileImage,
            #currentUserAltProfileImage: currentUserAltProfileImage,
          },
        ),
        returnValue: _i6.Future<_i3.ChatModel?>.value(),
      ) as _i6.Future<_i3.ChatModel?>);

  @override
  _i6.Future<List<String>> getChatParticipants(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatParticipants,
          [
            chatId,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> chatExists(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatExists,
          [
            chatId,
            userId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i3.ChatModel>> getUserChats(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserChats,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i6.Stream<List<_i3.ChatModel>>.empty(),
      ) as _i6.Stream<List<_i3.ChatModel>>);

  @override
  _i6.Future<_i3.ChatModel> createGroupChat({
    required String? creatorId,
    required String? groupName,
    required List<String>? memberIds,
    String? description,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroupChat,
          [],
          {
            #creatorId: creatorId,
            #groupName: groupName,
            #memberIds: memberIds,
            #description: description,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i6.Future<_i3.ChatModel>.value(_FakeChatModel_2(
          this,
          Invocation.method(
            #createGroupChat,
            [],
            {
              #creatorId: creatorId,
              #groupName: groupName,
              #memberIds: memberIds,
              #description: description,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i6.Future<_i3.ChatModel>);

  @override
  _i6.Future<_i3.ChatModel?> getChatByBubbleId(
    String? bubbleId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatByBubbleId,
          [
            bubbleId,
            currentUserId,
          ],
        ),
        returnValue: _i6.Future<_i3.ChatModel?>.value(),
      ) as _i6.Future<_i3.ChatModel?>);
}
