include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  plugins:
    - custom_lint
  errors:
    depend_on_referenced_packages: ignore
    invalid_annotation_target: ignore
    unnecessary_null_comparison: ignore
    unreachable_switch_default: ignore
    unused_field: ignore
    unused_local_variable: ignore
