// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7USz3YWFUmuVUwkHjHVdZEL6E5bDpbdI',
    appId: '1:756626341076:web:d690d481fdfaaeda008f41',
    messagingSenderId: '756626341076',
    projectId: 'herdapp-54e26',
    authDomain: 'herdapp-54e26.firebaseapp.com',
    storageBucket: 'herdapp-54e26.firebasestorage.app',
    measurementId: 'G-1C91GCWSY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vc2zH3zcpVQ1zKfUyjLcqqUSLW89Uqs',
    appId: '1:756626341076:android:c99d77cd05e082a1008f41',
    messagingSenderId: '756626341076',
    projectId: 'herdapp-54e26',
    storageBucket: 'herdapp-54e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9gPYtXUtGQii06zZRLXTIIbTTLXDHmU',
    appId: '1:756626341076:ios:210c584e514c5658008f41',
    messagingSenderId: '756626341076',
    projectId: 'herdapp-54e26',
    storageBucket: 'herdapp-54e26.firebasestorage.app',
    iosBundleId: 'com.herdco.herdapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7USz3YWFUmuVUwkHjHVdZEL6E5bDpbdI',
    appId: '1:756626341076:web:5b0ead5f8080eaa0008f41',
    messagingSenderId: '756626341076',
    projectId: 'herdapp-54e26',
    authDomain: 'herdapp-54e26.firebaseapp.com',
    storageBucket: 'herdapp-54e26.firebasestorage.app',
    measurementId: 'G-Q2RSJCND55',
  );
}
